import "./globals.css";
import { Poppins, Cinzel, Cinzel_Decorative, Dancing_Script } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dancingScript",
  display: "swap",
});
const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cinzel",
  display: "swap",
});
const cinzelDecorative = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--cinzelDecorative",
  display: "swap",
});

export const metadata = {
  title: "Nexus Traders",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}
          ${cinzel.variable}
          ${cinzelDecorative.variable}${dancingScript.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
